version: "3"
volumes:
  share:
    external: true
services:
  mysql-server:
    restart: always
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001]
    build: 
      context: .
      dockerfile: ./docker/Mysql.Dockerfile
    env_file:
      - ./docker/.env
    ports:
      - "3306:3306"
      - "33060:33060"
    working_dir: /var/lib/mysql
    volumes:
      - "./docker/volumes/mysql:/var/lib/mysql"   
    networks:
      - app_network 

  app-host:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    env_file:
      - ./docker/.env
    links:
      - mysql-server    
    depends_on:
      - mysql-server
    volumes:
      - ".:/app:rw"
    tty: true
    ports:
      - "4000:4000"
      - "30000-30020:30000-30020/tcp"
      - "30000-30020:30000-30020/udp" 
    networks:
      - app_network 


  app-client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    env_file:
      - ./docker/.env
    links:
      - app-host    
    depends_on:
      - app-host
    volumes:
      - ".:/app:rw"
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app_network 
    
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./docker/volumes/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app_network 
    

networks:
  app_network:
    external: true
  
 
    







 