version: "3"
volumes:
  share:
    external: true
services:
  mysql-server:
    restart: always
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: [mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001]
    build: 
      context: .
      dockerfile: ./docker/Mysql.Dockerfile
    env_file:
      - ./docker/.env
    ports:
      - "3306:3306"
      - "33060:33060"
    working_dir: /var/lib/mysql
    volumes:
      - "./docker/volumes/mysql:/var/lib/mysql"     

  mono-repo:
    build:
      context: .
      dockerfile: ./docker/mono-repo.Dockerfile
    env_file:
      - ./docker/.env
    links:
      - mysql-server    
    depends_on:
      - mysql-server
    volumes:
      - ".:/app:rw"
    tty: true
    entrypoint: ./entrypoint.sh
   

  # app-host:
  #   build:
  #     context: .
  #     dockerfile: ./docker/client.Dockerfile
  #   env_file:
  #     - ./docker/.env
  #   links:
  #     - mysql-server    
  #   depends_on:
  #     - mysql-server
  #   volumes:
  #     - ".:/app:rw"
  #   tty: true
  #   entrypoint: ./apps/host/entrypoint.sh
 

  # app-client:
  #   build:
  #     context: .
  #     dockerfile: ./docker/client.Dockerfile
  #   env_file:
  #     - ./docker/.env
  #   links:
  #     - app-host    
  #   depends_on:
  #     - app-host
  #   volumes:
  #     - ".:/app:rw"
  #   tty: true
  #   entrypoint: ./apps/client/entrypoint.sh
  
 
    







 